from __future__ import annotations

# Decision states
COMPUTED = "COMPUTED"
UNKNOWN = "UNKNOWN"

# Rule IDs
RULE_COMPUTED_OFFERS = "shopper_coupon_offer_set.computed_offers"
RULE_UNKNOWN_NO_OFFERS = "shopper_coupon_offer_set.unknown_no_offers"

# Driver codes
DRIVER_ELIGIBILITY_POLICY_ENFORCED = "ELIGIBILITY_POLICY_ENFORCED"
DRIVER_NOT_IN_WEEKLY_AD = "NOT_IN_WEEKLY_AD"
DRIVER_COUPON_DISCOUNT_APPLIED = "COUPON_DISCOUNT_APPLIED"
DRIVER_HIGH_AFFINITY = "HIGH_AFFINITY"
DRIVER_WEEKLY_AD_OVERLAP_EXCLUSION = "WEEKLY_AD_OVERLAP_EXCLUSION"
DRIVER_RECENT_PURCHASE_EXCLUSION = "RECENT_PURCHASE_EXCLUSION"
